### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by joao-pedrozo** [joao-pedrozo/shoppingify-client#1]
Write a README having the following: 

- Project logo at the top
- One image of the project;
- A description of the project;
- Chosen technologies;
- Link to the how-to-contribute guide wiki;
- How to install and execute the project (yarn, yarn dev, [...])
- Project dependencies (node version, [...])]
- Use emojis 😁

Technologies: Typescript, React, ChakraUI
Node version: [Node.js 14.6.0](https://nodejs.org/) or newer

If you have any suggestions about what we could remove/add/change, feel free to use the comments.

**Comment by oPablo-Santos** [comment]
Tenho interesse! RaiN_TheProdigy#0048
