### ISSUE TITLE
SideBar - Create Project Logo

### ISSUE THREAD

**Issue by joao-pedrozo** [joao-pedrozo/shoppingify-client#6]
# Side Menu Component

[Figma link](https://www.figma.com/file/kX8FNpYFVLI4ivuEQ6yGgS/Shopping-List?node-id=0-1&t=MIzEt8LwN646TNrE-0)

![image](https://user-images.githubusercontent.com/40037644/227084446-1a9a1e54-2d74-43c5-a8d2-bbfba56c522e.png)

1. ProjectLogo - This is the component that is going to show the project logo. (I recommend use the [Avatar](https://chakra-ui.com/docs/components/avatar/usage) component from Chakra).
**Acceptance criteria** - Should display the project logo in the described size in the figma link.

**Comment by Luizefz** [comment]
I can get this.
