### ISSUE TITLE
SideBar - Create NavigationItems 

### ISSUE THREAD

**Issue by joao-pedrozo** [joao-pedrozo/shoppingify-client#7]
# Side Menu Component
[Figma link](https://www.figma.com/file/kX8FNpYFVLI4ivuEQ6yGgS/Shopping-List?node-id=0-1&t=MIzEt8LwN646TNrE-0)

![image](https://user-images.githubusercontent.com/40037644/227085812-818ee2be-eb36-432e-91ac-09cc65bf1bd6.png)

1. NavigationItems - The wrapper that is going to have the 3 components of navigation
**Acceptance criteria** - Should contain the 3 navigation components inside and show the highlighted yellow bar at the currently selected item.
1.1 - NavigationItem - This is the navigation item inside the wrapper. Use the icons from the Figma link.
**Acceptance criteria** - Should display the specific icon component in a similar size related to the Figma link. Should also have the highlighted yellow bar on the left side when selected. Should also display the tooltip with the title of the item when hovered. Recommend using the [Tooltip](https://chakra-ui.com/docs/components/tooltip/usage) component for the Tooltip.

**Comment by Thiago-Mota-Santos** [comment]
i can get it
discord id: Thzinh#3271
